"use client";
/* eslint-disable import/no-unresolved */
import ReduxProvider from "@/store/ReduxProvider";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <main>{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
